//User List
export const DELETE_FROM_USER_LIST = "DELETE_FROM_USER_LIST";
export const UPDATE_USER_LIST = "UPDATE_USER_LIST";
export const CREATE_NEW_USER_IN_USER_LIST = "CREATE_NEW_USER_IN_USER_LIST";
export const FETCH_USER_LIST = "FETCH_USER_LIST";